config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
  # get '/', to: "pages#home", as: :root
  resources :trainers, only: %i[index show] do
    resources :pokemons, only: [:create]
  end
  resources :pokemons, only: :destroy do
    resources :pokemon_types, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :trainer
  has_many :pokemon_types, dependent: :destroy
  has_many :types, through: :pokemon_types
  validates :name, :image_url, presence: true
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :type
  belongs_to :pokemon
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  validates :banner_url, :name, presence: true
  has_many :pokemons # delete the child when removing self(trainer it self)
end

app/models/type.rb
class Type < ApplicationRecord
  validates :name, presence: true
  has_many :pokemon_types
  # has_many :pokemons, through: :pokemon_types
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pokemon_types_controller.rb
class PokemonTypesController < ApplicationController
  def new
    @pokemon = Pokemon.find(params[:pokemon_id])
    @pokemon_type = PokemonType.new
  end

  def create
    @pokemon = Pokemon.find(params[:pokemon_id])

    # @pokemon_type = PokemonType.new(pokemon_type_params)
    # @pokemon_type.pokemon = @pokemon
    # raise
    # if @pokemon_type.save
    # else
    #   render 'new', status: :unprocessable_entity
    # end

    types = Type.where(id: params[:pokemon_type][:type])
    types.each do |type|
      PokemonType.create(pokemon: @pokemon, type: type)
    end
    redirect_to trainer_path(@pokemon.trainer)
  end

  private

  def pokemon_type_params
    params.require(:pokemon_type).permit(:type_id)
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def create
    # 0. find the right trainer
    @trainer = Trainer.find(params[:trainer_id])
    # 1 .initialize the new pokemon with the information coming from the form
    @pokemon = Pokemon.new(pokemon_params)
    # 2. assign the right trainer
    @pokemon.trainer = @trainer

    if @pokemon.save
      redirect_to trainer_path(@trainer)
    else
      # Render doesn't trigger a new HTTP request
      # gets the HTML and siplay on the page
      # uses the variable inside THIS ACTION
      # to render the html required
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @pokemon = Pokemon.find(params[:id])
    @pokemon.destroy

    redirect_to trainer_path(@pokemon.trainer)
  end

  private

  def pokemon_params
    # params
#     {"authenticity_token"=>"[FILTERED]",
#  "pokemon"=>{"name"=>"Brok", "image_url"=>"https://static1.srcdn.com/wordpress/wp-content/uploads/2016/11/Brock-Pokemon-Series.jpg"},
#  "commit"=>"Create Pokemon",
#  "trainer_id"=>"5"}
#   params.require(:pokemon) => {"name"=>"Brok", "image_url"=>"https://static1.srcdn.com/wordpress/wp-content/uploads/2016/11/Brock-Pokemon-Series.jpg"},
    params.require(:pokemon).permit(:name, :image_url)
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  def index
    @trainer = Trainer.all
  end
  def show
    @trainer = Trainer.find(params[:id])
    @pokemon = Pokemon.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pokemon_types_helper.rb
module PokemonTypesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GottaCatchEmAll</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1 class="text-center">Gotta Catch'em All</h1>
  <p class="text-center"><%= link_to 'See trainers', trainers_path, class: 'btn btn-magic' %></p>


  <h2 class="mt-5">Things below are part of our Rails Assets lecture 😁</h2>
  <i class="fa-solid fa-magnifying-glass"></i>
  <%= icon 'fa-solid', 'circle' %>
  <img src="/app/assets/images/logo.png-p91832479hjbsdboiyh2389t3e3eybd" alt="">
  <%= image_tag 'logos/logo.png', alt: 'Le Wagon logo', width: '200px', class: 'img-circle', id: 'logoImg' %>
  <div class="logo"></div>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-magic" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Launch demo modal
  </button>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/pokemon_types/new.html.erb
<div class="container">
  <h1>Add type to Pokemon</h1>
  <%= simple_form_for [@pokemon, @pokemon_type] do |f| %>
    <%= f.input :type, collection: Type.all, input_html: { multiple: true  } %>
    <%= f.submit %>
  <% end %>

</div>

app/views/pokemons/new.html.erb
<div class="container">
  <h1>Add your pokemon</h1>
  <%# /pokemons %>
  <%= simple_form_for([@trainer, @pokemon]) do |f| %>
    <%= f.input :name %>
    <%= f.input :image_url %>
    <%= f.submit %>
  <% end %>

</div>

app/views/trainers/index.html.erb
<h1 class="text-center text-magic">Trainers</h1>
<div class="container">
  <div class="row">
    <% @trainer.each do |trainer| %>
      <div class="col-12 col-md-6 col-lg-4">
        <%= link_to trainer_path(trainer) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= trainer.banner_url %>)">
            <%= trainer.name %>
          </div>
        <% end %>

      </div>
    <% end %>
  </div>
</div>

app/views/trainers/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @trainer.banner_url %>);">
  <div class="container">
    <h1><%= @trainer.name %></h1>
  </div>
</div>



<div class="container mt-3">
  <div class="row">
    <div class="col-8">
      <div class="row">
        <% @trainer.pokemons.each do |pokemon| %>
          <div class="col-4">
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= pokemon.image_url %>)">
              <%= pokemon.name %>
              <%= link_to pokemon_path(pokemon), data: { turbo_method: :delete, turbo_confirm: "Are you sure? It's so cute"}, class: 'card-remove-link' do %>
                <%= icon('fa-solid', 'trash', class: 'fs-6') %>
              <% end %>
              <div class="poke-types">
                <% pokemon.types.each do |type| %>
                  <small class="type-pill"><%= type.name %></small>
                <% end %>
              </div>
              <%= link_to 'Add type', new_pokemon_pokemon_type_path(pokemon) %>
            </div>
          </div>
        <% end %>
      </div>

    </div>
    <div class="col-4">
      <%= simple_form_for([@trainer, @pokemon]) do |f| %>
        <%= f.input :name %>
        <%= f.input :image_url %>
        <%= f.submit class: 'btn btn-magic' %>
      <% end %>
    </div>
  </div>
</div>